---
env:
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.3
  - PUPPET_VERSION=3.4.2
language: ruby
notifications: ~
rvm:
  - "1.8.7"
  - "1.9.3"
script: "SPEC_OPTS='--format documentation' bundle exec rake spec && bundle exec rake lint"
